config/routes.rb
Rails.application.routes.draw do
  
  resources :hits

  devise_for :users
  root 'static_pages#index'
end

app/models/hit.rb
class Hit < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :hits
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update).concat([:name, :avatar_url])
  end
end

app/controllers/hits_controller.rb
class HitsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_hit, only: [:show, :edit, :update, :destroy]

  # GET /hits
  # GET /hits.json
  def index
    @hits = Hit.all
  end

  # GET /hits/1
  # GET /hits/1.json
  def show
  end

  # GET /hits/new
  def new
    @hit = current_user.hits.build
  end

  # GET /hits/1/edit
  def edit
  end

  # POST /hits
  # POST /hits.json
  def create
    @hit = current_users.hits.build(hit_params)

    respond_to do |format|
      if @hit.save
        format.html { redirect_to @hit, notice: 'Hit was successfully created.' }
        format.json { render :show, status: :created, location: @hit }
      else
        format.html { render :new }
        format.json { render json: @hit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hits/1
  # PATCH/PUT /hits/1.json
  def update
    respond_to do |format|
      if @hit.update(hit_params)
        format.html { redirect_to @hit, notice: 'Hit was successfully updated.' }
        format.json { render :show, status: :ok, location: @hit }
      else
        format.html { render :edit }
        format.json { render json: @hit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hits/1
  # DELETE /hits/1.json
  def destroy
    @hit.destroy
    respond_to do |format|
      format.html { redirect_to hits_url, notice: 'Hit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hit
      @hit = current_user.hits.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hit_params
      params.require(:hit).permit(:message)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hits_helper.rb
module HitsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/hits/_form.html.erb
<%= form_for(@hit) do |f| %>
  <% if @hit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hit.errors.count, "error") %> prohibited this hit from being saved:</h2>

      <ul>
      <% @hit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_area :message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hits/edit.html.erb
<h1>Editing hit</h1>

<%= render 'form' %>

<%= link_to 'Show', @hit %> |
<%= link_to 'Back', hits_path %>

app/views/hits/index.html.erb
<h1>Listing hits</h1>

<table>
  <thead>
    <tr>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hits.each do |hit| %>
      <tr>
        <td><%= hit.message %></td>
        <td><%= link_to 'Show', hit %></td>
        <td><%= link_to 'Edit', edit_hit_path(hit) %></td>
        <td><%= link_to 'Destroy', hit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hit', new_hit_path %>

app/views/hits/new.html.erb
<h1>New hit</h1>

<%= render 'form' %>

<%= link_to 'Back', hits_path %>

app/views/hits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @hit.message %>
</p>

<%= link_to 'Edit', edit_hit_path(@hit) %> |
<%= link_to 'Back', hits_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twezzer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class='navbar navbar_default'>
    <% link_to('Twezzer', root_path, class: 'navbar-brand') %>
  <ul class='nav navbar-nav'>
    <% if user_signed_in? %>
    <li><%= link_to('Edit Account', edit_user_registration_path) %></li>
    <li><%= link_to('Logout', destroy_user_session_path, method: :delete) %></li>
  <% else %>
    <li><%= link_to('Sign Up', new_user_registration_path) %></li>
    <li><%= link_to('Sign In', new_user_session_path) %></li>
  <% end %>
  </ul>
  <div class='container'>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </div>
<section class='container'>
  <%= yield %>
</section>


</body>
</html>

app/views/static_pages/index.html.erb
<h1>Yo</h1>